#!/bin/bash
### BY GOD OF SKY ###
clear
echo -e "\033[1;31m /////////// { TWEAKER QUICK } /////////// "
if [[ `grep -c "^#PH56" /etc/sysctl.conf` -eq 1 ]]
then
echo -e "\033[01;34m===================================================================="
	echo -e "\033[1;33mCONFIGURAÇÃO TWEAKER JA APLICADO !\033[1;37m"
echo -e "\033[01;34m====================================================================\033[1;37m"
	echo ""
	read -p "DESEJA REMOVER CONFIGURAÇÃO TWEAKER? [sim/nao]: " -e -i nao resposta0
	if [[ "$resposta0" = 'sim' ]]; then
		grep -v "^#PH56
#"1"
fs.nr_open = 1048576
fs.file-max = 1048576
vm.vfs_cache_pressure = 200
vm.swappiness = 100
vm.page-cluster = 16
vm.dirty_ratio = 1
vm.dirty_background_ratio = 1
vm.overcommit_memory = 1

#"2"

kernel.sched_migration_cost_ns = 800000000
kernel.sched_latency_ns = 1000000
kernel.sched_nr_migrate = 32768
kernel.sched_wakeup_granularity_ns = 10000
kernel.threads-max = 16384
kernel.pid_max = 16384
kernel.pty.max = 8192
kernel.sched_tunable_scaling = 1
kernel.sched_rt_runtime_us = -1
kernel.sched_rt_period_us = -1
kernel.sched_rr_timeslice_ms = -1
kernel.sched_autogroup_enabled = 0

#"3"

net.ipv4.tcp_mem = 10000000 10000000 10000000
net.ipv4.udp_mem = 10000000 10000000 10000000
net.ipv4.tcp_wmem = 4096 524288 11960320
net.ipv4.tcp_rmem = 4096 524288 11960320
net.core.rmem_default = 11960320
net.core.wmem_default = 11960320
net.core.wmem_max = 11960320
net.core.rmem_max = 11960320
net.ipv4.udp_wmem_min = 16384
net.ipv4.udp_rmem_min = 16384

#"4"

net.core.netdev_max_backlog = 32768
net.core.flow_limit_table_len = 32768
net.core.optmem_max = 16384
net.core.somaxconn = 16384
net.unix.max_dgram_qlen = 16384
net.core.netdev_budget = 16384
net.core.rps_sock_flow_entries = 4096
net.core.dev_weight = 1024
net.core.busy_read = 25
net.core.busy_poll = 25

#"5"

net.ipv4.tcp_congestion_control = illinois
net.ipv4.tcp_allowed_congestion_control = illinois
net.core.default_qdisc = fq

#"6"

net.ipv4.route.mtu_expires = 1800
net.ipv4.tcp_keepalive_probes = 1024
net.ipv4.tcp_synack_retries = 1024
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_intvl = 120
net.ipv4.tcp_syn_retries = 100
net.ipv4.tcp_probe_interval = 30
net.ipv4.tcp_fin_timeout = 15

#"7"

net.ipv4.ip_local_port_range = 60000 65535
net.ipv4.tcp_max_syn_backlog = 32768
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_max_tw_buckets = 16384
net.ipv4.tcp_base_mss = 1460
net.ipv4.tcp_max_orphans = 8192
net.ipv4.tcp_min_rtt_wlen = 1024
net.ipv4.tcp_reordering = 1024
net.ipv4.tcp_min_snd_mss = 1024
net.ipv4.tcp_min_tso_segs = 1024
net.ipv4.route.min_adv_mss = 1024
net.ipv4.tcp_probe_threshold = 1024
net.ipv4.tcp_fastopen = 1024
net.ipv4.tcp_pacing_ca_ratio = 900
net.ipv4.tcp_pacing_ss_ratio = 900
net.ipv4.tcp_max_reordering = 600
net.ipv4.tcp_window_scaling = 8
net.ipv4.tcp_tso_win_divisor = 8
net.ipv4.tcp_adv_win_scale = 8
net.ipv4.tcp_mtu_probing = 2
net.ipv4.tcp_orphan_retries = 2
net.ipv4.tcp_abort_on_overflow = 1
net.ipv4.fwmark_reflect = 1
net.ipv4.ip_forward_use_pmtu = 1
net.ipv4.ip_forward = 1
net.ipv4.tcp_thin_linear_timeouts = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_early_retrans = 1
net.ipv4.fib_multipath_use_neigh = 1
net.ipv4.ipfrag_time = 1
net.ipv4.xfrm4_gc_thresh = 0
net.ipv4.tcp_app_win = 0
net.ipv4.tcp_ecn_fallback = 0
net.ipv4.tcp_invalid_ratelimit = 0
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_moderate_rcvbuf = 0
net.ipv4.tcp_ecn = 0
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_frto = 0

#"8"

net.ipv4.route.max_size = 32768
net.ipv4.route.gc_thresh = 16384
net.ipv4.route.gc_elasticity = 16384
net.ipv4.route.gc_interval = 120
net.ipv4.route.mtu_expires = 15
net.ipv4.route.gc_timeout = 15
net.ipv4.route.min_adv_mss = 1024
net.ipv4.route.min_pmtu = 1024

#"9"

net.ipv4.neigh.default.unres_qlen_bytes = 11960320
net.ipv4.neigh.default.unres_qlen = 32768
net.ipv4.neigh.default.proxy_qlen = 16384
net.ipv4.neigh.default.gc_thresh3 = 16384
net.ipv4.neigh.default.gc_thresh2 = 8192
net.ipv4.neigh.default.gc_thresh1 = 4096
net.ipv4.neigh.default.gc_stale_time = 300
net.ipv4.neigh.default.gc_interval = 120

#"10"

net.ipv4.neigh.eth0.proxy_qlen = 16777216
net.ipv4.neigh.eth0.unres_qlen_bytes = 16777216
net.ipv4.neigh.eth0.gc_stale_time = 86400
net.ipv4.neigh.eth0.unres_qlen = 32768

#"11"

net.ipv4.neigh.lo.unres_qlen_bytes = 11960320
net.ipv4.neigh.lo.unres_qlen = 32768
net.ipv4.neigh.lo.proxy_qlen = 16384
net.ipv4.neigh.lo.gc_stale_time = 300

#"12"

net.netfilter.nf_conntrack_max = 33554432
net.netfilter.nf_conntrack_tcp_max_retrans = 8192
net.netfilter.nf_conntrack_tcp_max_retrans = 7200
net.netfilter.nf_conntrack_tcp_be_liberal = 1
net.netfilter.nf_conntrack_tcp_timeout_established = 15
net.netfilter.nf_conntrack_udp_timeout = 15
net.netfilter.nf_conntrack_udp_timeout_stream = 15
net.netfilter.nf_conntrack_tcp_timeout_syn_recv = 15
net.netfilter.nf_conntrack_tcp_timeout_syn_sent = 15
net.netfilter.nf_conntrack_tcp_timeout_established = 15
net.netfilter.nf_conntrack_tcp_timeout_close = 15
net.netfilter.nf_conntrack_tcp_timeout_close_wait = 15
net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 15

#"13"

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1" /etc/sysctl.conf > /tmp/syscl && mv /tmp/syscl /etc/sysctl.conf

sysctl -p /etc/sysctl.conf > /dev/null
echo -n > /etc/sysctl.conf
crontab -u root -l | grep -v '@reboot sleep 10s && /bin/tweaker'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s && /bin/acksyshttpack'  | crontab -u root -
		echo ""
	echo -e "\033[1;32mCONFIGURAÇÃO DE TWEAKER REMOVIDO COM SUCESSO !"
		echo ""
echo -e "\033[1;31mVOLTANDO AO MENU"
sleep 3s
		menu
	else
sleep 3s
menu
	fi
else
echo -e "\033[01;34m===================================================================="
echo -e "\033[1;33mAVISO ! >>>      \033[1;37mESSE SCRIPT LIDAR COM    \033[1;32m(TCP) + \033[1;32m(UDP) + \033[1;32m(MEMORIA)"
echo -e "\033[01;34m==================================================================== \033[1;37m"
	read -p "DESEJAR INSTALAR TWEAKER ? [sim/nao]: " -e -i sim resposta
	if [[ "$resposta" = 'sim' ]]; then
	echo ""
	echo " " >> /etc/sysctl.conf
	echo "#PH56" >> /etc/sysctl.conf

#"1"

echo "fs.nr_open = 1048576
fs.file-max = 1048576
vm.vfs_cache_pressure = 200
vm.swappiness = 1
vm.page-cluster = 16
vm.dirty_ratio = 1
vm.dirty_background_ratio = 1
vm.overcommit_memory = 1

#"2"

kernel.sched_migration_cost_ns = 800000000
kernel.sched_latency_ns = 1000000
kernel.sched_nr_migrate = 32768
kernel.sched_wakeup_granularity_ns = 10000
kernel.threads-max = 16384
kernel.pid_max = 16384
kernel.pty.max = 8192
kernel.sched_tunable_scaling = 1
kernel.sched_rt_runtime_us = -1
kernel.sched_rt_period_us = -1
kernel.sched_rr_timeslice_ms = -1
kernel.sched_autogroup_enabled = 0

#"3"

net.ipv4.tcp_mem = 10000000 10000000 10000000
net.ipv4.udp_mem = 10000000 10000000 10000000
net.ipv4.tcp_wmem = 4096 524288 11960320
net.ipv4.tcp_rmem = 4096 524288 11960320
net.core.rmem_default = 11960320
net.core.wmem_default = 11960320
net.core.wmem_max = 11960320
net.core.rmem_max = 11960320
net.ipv4.udp_wmem_min = 16384
net.ipv4.udp_rmem_min = 16384

#"4"

net.core.netdev_max_backlog = 32768
net.core.flow_limit_table_len = 32768
net.core.optmem_max = 16384
net.core.somaxconn = 16384
net.unix.max_dgram_qlen = 16384
net.core.netdev_budget = 16384
net.core.rps_sock_flow_entries = 4096
net.core.dev_weight = 1024
net.core.busy_read = 25
net.core.busy_poll = 25

#"5"

net.ipv4.tcp_congestion_control = illinois
net.ipv4.tcp_allowed_congestion_control = illinois
net.core.default_qdisc = fq

#"6"
net.ipv4.route.mtu_expires = 1800
net.ipv4.tcp_keepalive_probes = 1024
net.ipv4.tcp_synack_retries = 1024
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_intvl = 120
net.ipv4.tcp_syn_retries = 100
net.ipv4.tcp_probe_interval = 30
net.ipv4.tcp_fin_timeout = 15

#"7"

net.ipv4.ip_local_port_range = 60000 65535
net.ipv4.tcp_max_syn_backlog = 32768
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_max_tw_buckets = 16384
net.ipv4.tcp_base_mss = 1460
net.ipv4.tcp_max_orphans = 8192
net.ipv4.tcp_min_rtt_wlen = 1024
net.ipv4.tcp_reordering = 1024
net.ipv4.tcp_min_snd_mss = 1024
net.ipv4.tcp_min_tso_segs = 1024
net.ipv4.route.min_adv_mss = 1024
net.ipv4.tcp_probe_threshold = 1024
net.ipv4.tcp_fastopen = 1024
net.ipv4.tcp_pacing_ca_ratio = 900
net.ipv4.tcp_pacing_ss_ratio = 900
net.ipv4.tcp_max_reordering = 600
net.ipv4.tcp_window_scaling = 8
net.ipv4.tcp_tso_win_divisor = 8
net.ipv4.tcp_adv_win_scale = 8
net.ipv4.tcp_mtu_probing = 2
net.ipv4.tcp_orphan_retries = 2
net.ipv4.tcp_abort_on_overflow = 1
net.ipv4.fwmark_reflect = 1
net.ipv4.ip_forward_use_pmtu = 1
net.ipv4.ip_forward = 1
net.ipv4.tcp_thin_linear_timeouts = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_early_retrans = 1
net.ipv4.fib_multipath_use_neigh = 1
net.ipv4.ipfrag_time = 1
net.ipv4.xfrm4_gc_thresh = 0
net.ipv4.tcp_app_win = 0
net.ipv4.tcp_ecn_fallback = 0
net.ipv4.tcp_invalid_ratelimit = 0
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_moderate_rcvbuf = 0
net.ipv4.tcp_ecn = 0
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_frto = 0

#"8"

net.ipv4.route.max_size = 32768
net.ipv4.route.gc_thresh = 16384
net.ipv4.route.gc_elasticity = 16384
net.ipv4.route.gc_interval = 120
net.ipv4.route.mtu_expires = 15
net.ipv4.route.gc_timeout = 15
net.ipv4.route.min_adv_mss = 1024
net.ipv4.route.min_pmtu = 1024

#"9"

net.ipv4.neigh.default.unres_qlen_bytes = 11960320
net.ipv4.neigh.default.unres_qlen = 32768
net.ipv4.neigh.default.proxy_qlen = 16384
net.ipv4.neigh.default.gc_thresh3 = 16384
net.ipv4.neigh.default.gc_thresh2 = 8192
net.ipv4.neigh.default.gc_thresh1 = 4096
net.ipv4.neigh.default.gc_stale_time = 300
net.ipv4.neigh.default.gc_interval = 120

#"10"

net.ipv4.neigh.eth0.proxy_qlen = 16777216
net.ipv4.neigh.eth0.unres_qlen_bytes = 16777216
net.ipv4.neigh.eth0.gc_stale_time = 86400
net.ipv4.neigh.eth0.unres_qlen = 32768

#"11"

net.ipv4.neigh.lo.unres_qlen_bytes = 11960320
net.ipv4.neigh.lo.unres_qlen = 32768
net.ipv4.neigh.lo.proxy_qlen = 16384
net.ipv4.neigh.lo.gc_stale_time = 300

#"12"

net.netfilter.nf_conntrack_max = 33554432
net.netfilter.nf_conntrack_tcp_max_retrans = 8192
net.netfilter.nf_conntrack_tcp_max_retrans = 7200
net.netfilter.nf_conntrack_tcp_be_liberal = 1
net.netfilter.nf_conntrack_tcp_timeout_established = 15
net.netfilter.nf_conntrack_udp_timeout = 15
net.netfilter.nf_conntrack_udp_timeout_stream = 15
net.netfilter.nf_conntrack_tcp_timeout_syn_recv = 15
net.netfilter.nf_conntrack_tcp_timeout_syn_sent = 15
net.netfilter.nf_conntrack_tcp_timeout_established = 15
net.netfilter.nf_conntrack_tcp_timeout_close = 15
net.netfilter.nf_conntrack_tcp_timeout_close_wait = 15
net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 15

#"13"

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
acksyshttpack > /dev/null 2>&1
sysctl -p /etc/sysctl.conf > /dev/null
(crontab -l; echo "@reboot sleep 10s && /bin/tweaker") | crontab - > /dev/null 2>&1
(crontab -l; echo "@reboot sleep 10s && /bin/acksyshttpack") | crontab - > /dev/null 2>&1
	echo -e "\033[1;32mCONFIGURAÇÃO DE TWEAKER APLICADO COM SUCESSO !"
	else
		echo ""
		echo -e "\033[1;31mA INSTALACAO FOI CANCELADA !"
		echo ""
	fi
fi
sleep 5s;menu

