#!/bin/bash
clear
rm -f multiportas*
apt install python3.7 -y > /dev/null 2>&1
echo -e "\033[1;33m REINICIE O SERVIDOR, APOS O PROCEDIMENTO !\033[1;32m"
echo ""
sleep 3s
echo ""
echo -e "\033[1;33m SCRIPT APENAS PARA USUARIOS \033[1;32m(SSHPLUS)\033[1;32m"
sleep 6s
echo ""
echo -e "\033[1;33mREMOVENDO \033[1;31mWSPROXY.PY \033[1;37m+ \033[1;31mPROXY.PY"
sleep 3s
cd /etc/SSHPlus && rm -rf wsproxy.py*
cd /etc/SSHPlus && rm -rf proxy.py*
echo  ""
echo -e "\033[1;33mINSTALANDO PROXY.PY \033[1;32m(MODO WEBSOCKET)"
sleep 3s
cd /etc/SSHPlus && wget https://raw.githubusercontent.com/ACKHTTP/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/PYTHON%20SOCKS/proxy.py > /dev/null 2>&1
cd /etc/SSHPlus && chmod +x proxy.py
echo ""
sleep 5s
clear
echo -e "\033[1;33mMODIFACOES FINALIZADAS !\033[1;32m"
sleep 3s
echo ""
echo -e "\033[1;36m QUANDO ABRIR O MODO DE CONEXAO >>> ( PROXY SOCKS )\033[1;32m"
echo -e "\033[1;36m SELECIONE A OPCAO (SOCKS SSH) PARA UTILIZAR.\033[1;32m"
echo ""
echo -e "\033[1;36m PARA VOLTAR, DIGITE ( menu )\033[1;37m"
echo "" 
sleep 3s
echo ""
echo ""
